name: Lint test & build

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: node:22.9-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup node
        uses: actions/setup-node@v5
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Install dependencies
        shell: sh
        run: npm ci
      - name: Run linter
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    container:
      image: node:22.9-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup node
        uses: actions/setup-node@v5
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Install dependencies
        shell: sh
        run: npm ci
      - name: Run tests
        run: npm run test
  build:
    runs-on: ubuntu-latest
    container:
      image: node:22.9-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup node
        uses: actions/setup-node@v5
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Install dependencies
        shell: sh
        run: npm ci
      - name: Build project
        run: npm run build
